name: Canary Workflow

on:
  push:
    branches:
      - canary

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

  prepare-stable:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Prepare code for Stable
      run: echo "Code is ready to be merged into Stable"

  notify:
    runs-on: ubuntu-latest
    needs: prepare-stable
    steps:
    - name: Notify
      run: echo "Code is ready to be merged into Stable"